<?php

require_once 'saysomethingnice.php';

$ip = ip2long('75.181.37.52');
add_quote("mumumummumumumumumummumumumumumumummumumumumumu", 'carrie@icculus.org', $ip);
add_quote("I could get lost in your eyes for days and days.", 'carrie@icculus.org', $ip);
add_quote("Have you lost weight?", 'carrie@icculus.org', $ip);
add_quote("Your friends aren't as hot as you.", 'carrie@icculus.org', $ip);
add_quote("I'm obviously wrong in this scenario, and bow to your superior intellect.", 'carrie@icculus.org', $ip);
add_quote("I love your cats.", 'carrie@icculus.org', $ip);
add_quote("Your mom is totally wrong about that.", 'carrie@icculus.org', $ip);
add_quote("You don't look fat in that.", 'carrie@icculus.org', $ip);
add_quote("Your cat could kick my dog's ass any day.", 'carrie@icculus.org', $ip);
add_quote("Of course your cats can sleep in bed with us, they are part of the family.", 'carrie@icculus.org', $ip);
add_quote("Your cats are totally smarter than my dog.", 'carrie@icculus.org', $ip);
add_quote("Your smile stays with my all day.", 'carrie@icculus.org', $ip);
add_quote("I feel like I can tell you anything.", 'carrie@icculus.org', $ip);
add_quote("I can tell you things that I've never told anyone else.", 'carrie@icculus.org', $ip);
add_quote("I didn't know what love was until I meet you.", 'carrie@icculus.org', $ip);
add_quote("You totally get me.", 'carrie@icculus.org', $ip);
add_quote("I can be myself around you.", 'carrie@icculus.org', $ip);
add_quote("I can see my future in you.", 'carrie@icculus.org', $ip);
add_quote("I've never been this happy before.", 'carrie@icculus.org', $ip);
add_quote("No one has ever made me this happy.", 'carrie@icculus.org', $ip);
add_quote("I can't imagine being happy without you in my life.", 'carrie@icculus.org', $ip);
add_quote("Your jokes make me pee myself a little.", 'carrie@icculus.org', $ip);
add_quote("I love watching chick flicks with you.", 'carrie@icculus.org', $ip);
add_quote("Everytime we watch The Notebook together, I feel closer to you.", 'carrie@icculus.org', $ip);
add_quote("Thank you for watching football with me.", 'carrie@icculus.org', $ip);
add_quote("Have you been working out, because those pants look hot on you!", 'carrie@icculus.org', $ip);
add_quote("That shirt really brings out the color in your eyes.", 'carrie@icculus.org', $ip);
add_quote("Is that a new outfit? You look great!", 'carrie@icculus.org', $ip);
add_quote("Those shoes are so you.", 'carrie@icculus.org', $ip);
add_quote("You can never have too many shoes.", 'carrie@icculus.org', $ip);
add_quote("That necklace looks great on you.", 'carrie@icculus.org', $ip);
add_quote("It doesn't matter what it costs.", 'carrie@icculus.org', $ip);
add_quote("You deserve to go shopping.", 'carrie@icculus.org', $ip);
add_quote("You can totally wear red.", 'carrie@icculus.org', $ip);
add_quote("You are so funny.", 'carrie@icculus.org', $ip);
add_quote("You can always make me laugh.", 'carrie@icculus.org', $ip);
add_quote("It's impossible to be in a bad mood when I'm around you.", 'carrie@icculus.org', $ip);
add_quote("You make anything seem possible.", 'carrie@icculus.org', $ip);
add_quote("Thank you for believing in me.", 'carrie@icculus.org', $ip);
add_quote("You are so much fun to shop with.", 'carrie@icculus.org', $ip);
add_quote("Your hair smells so good. ", 'carrie@icculus.org', $ip);
add_quote("You hair is so soft.", 'carrie@icculus.org', $ip);
add_quote("Your haircut looks great!", 'carrie@icculus.org', $ip);
add_quote("You never have a bad hair day.", 'carrie@icculus.org', $ip);
add_quote("You are good person.", 'carrie@icculus.org', $ip);
add_quote("I never think about my exes.", 'carrie@icculus.org', $ip);
add_quote("I had girlfriends before you? Really? Because I don't remember them.", 'carrie@icculus.org', $ip);
add_quote("You are so beautiful.", 'carrie@icculus.org', $ip);
add_quote("You are so beautiful when you laugh.", 'carrie@icculus.org', $ip);
add_quote("You are so beautiful when you smile.", 'carrie@icculus.org', $ip);
add_quote("You are beautiful even when we are fighting.", 'carrie@icculus.org', $ip);
add_quote("I can't stay mad at you.", 'carrie@icculus.org', $ip);
add_quote("You are such a good friend.", 'carrie@icculus.org', $ip);
add_quote("Thank you for listening to me, I really needed someone to talk to.", 'carrie@icculus.org', $ip);
add_quote("You are a great listener. ", 'carrie@icculus.org', $ip);
add_quote("You always make me feel better.", 'carrie@icculus.org', $ip);
add_quote("You always think of the most thoughtful things to do.", 'carrie@icculus.org', $ip);
add_quote("You give the best presents.", 'carrie@icculus.org', $ip);
add_quote("You make the best sandwiches.", 'carrie@icculus.org', $ip);
add_quote("You are such a better cook than my mom.", 'carrie@icculus.org', $ip);
add_quote("I don't think that cake looks lopsided.", 'carrie@icculus.org', $ip);
add_quote("My parents love you.", 'carrie@icculus.org', $ip);
add_quote("My friends think you're hot.", 'carrie@icculus.org', $ip);
add_quote("My friends always say how lucky I am to have you.", 'carrie@icculus.org', $ip);
add_quote("I can't believe I was lucky enough to find you.", 'carrie@icculus.org', $ip);
add_quote("I'd rather hang out with you than with my friends.", 'carrie@icculus.org', $ip);
add_quote("You're right, my friends are so immature.", 'carrie@icculus.org', $ip);
add_quote("Your'e right.", 'carrie@icculus.org', $ip);
add_quote("You always know where I left my keys.", 'carrie@icculus.org', $ip);
add_quote("That was the best meal I've ever had.", 'carrie@icculus.org', $ip);
add_quote("Yes, we can get a maid.", 'carrie@icculus.org', $ip);
add_quote("I put down the seat.", 'carrie@icculus.org', $ip);
add_quote("I love picking out paint colors with you.", 'carrie@icculus.org', $ip);
add_quote("This is exactly what I wanted to do this weekend.", 'carrie@icculus.org', $ip);
add_quote("I've never seen a bad picture of you.", 'carrie@icculus.org', $ip);
add_quote("Do you want me to pick up dinner on the way home?", 'carrie@icculus.org', $ip);
add_quote("No, I don't mind buying tampons for you.", 'carrie@icculus.org', $ip);
add_quote("Is your butt getting smaller?", 'carrie@icculus.org', $ip);
add_quote("I don't even look at other women anymore.", 'carrie@icculus.org', $ip);
add_quote("No, I'm not bored.", 'carrie@icculus.org', $ip);
add_quote("Can we go shopping again this weekend?", 'carrie@icculus.org', $ip);
add_quote("That's not too much to spend on a haircut.", 'carrie@icculus.org', $ip);
add_quote("It feels like I've known you forever.", 'carrie@icculus.org', $ip);
add_quote("I love your Celine Dion CD.", 'carrie@icculus.org', $ip);
add_quote("You look younger every year.", 'carrie@icculus.org', $ip);
add_quote("I'm more in love with you now that I was when I married you.", 'carrie@icculus.org', $ip);
add_quote("That's a shadow, not a wrinkle.", 'carrie@icculus.org', $ip);
add_quote("Yes, I'm watering your plants.", 'carrie@icculus.org', $ip);
add_quote("I was wrong.", 'carrie@icculus.org', $ip);
add_quote("I should have listened to you.", 'carrie@icculus.org', $ip);
add_quote("You're too good for that job.", 'carrie@icculus.org', $ip);
add_quote("Those people at your work are idiots.", 'carrie@icculus.org', $ip);
add_quote("Your boss doesn't know what she's talking about.", 'carrie@icculus.org', $ip);
add_quote("You should be making more money.", 'carrie@icculus.org', $ip);
add_quote("You are a saint to put up with those people at work.", 'carrie@icculus.org', $ip);
add_quote("That perfume smells great on you.", 'carrie@icculus.org', $ip);
add_quote("I love the way you smell when you get out of the shower.", 'carrie@icculus.org', $ip);
add_quote("You never look sexier that when you are just waking up.", 'carrie@icculus.org', $ip);
add_quote("I could watch you sleep forever.", 'carrie@icculus.org', $ip);
add_quote("Don't get up, I want to cuddle some more.", 'carrie@icculus.org', $ip);
add_quote("I like falling asleep while holding each other too.", 'carrie@icculus.org', $ip);
add_quote("Don't go home yet.", 'carrie@icculus.org', $ip);
add_quote("I miss you.", 'carrie@icculus.org', $ip);
add_quote("You make ever day sunnier.", 'carrie@icculus.org', $ip);
add_quote("Let's go take a walk in the rain together.", 'carrie@icculus.org', $ip);
add_quote("Take my jacket, you look cold.", 'carrie@icculus.org', $ip);
add_quote("I'l cook dinner tonight.", 'carrie@icculus.org', $ip);
add_quote("I like your family.", 'carrie@icculus.org', $ip);
add_quote("I feel so close to you.", 'carrie@icculus.org', $ip);
add_quote("We are the best couple I know.", 'carrie@icculus.org', $ip);
add_quote("There is never a dull moment when we are together. ", 'carrie@icculus.org', $ip);
add_quote("I miss you when I'm not near you.", 'carrie@icculus.org', $ip);
add_quote("You feel so great.", 'carrie@icculus.org', $ip);
add_quote("You give the best hugs.", 'carrie@icculus.org', $ip);
add_quote("When you hug me I feel like everything will be ok.", 'carrie@icculus.org', $ip);
add_quote("When I'm with you it feels like no one else is around.", 'carrie@icculus.org', $ip);
add_quote("You were the most beautiful woman there.", 'carrie@icculus.org', $ip);
add_quote("You make everything more fun.", 'carrie@icculus.org', $ip);
add_quote("You are so good at your job.", 'carrie@icculus.org', $ip);
add_quote("I could kiss you forever.", 'carrie@icculus.org', $ip);
add_quote("You always say the right things.", 'carrie@icculus.org', $ip);
add_quote("You always know exactly what to say.", 'carrie@icculus.org', $ip);
add_quote("You know what I'm thinking before I do.", 'carrie@icculus.org', $ip);
add_quote("I feel like we've always been together.", 'carrie@icculus.org', $ip);
add_quote("I can't imagine my life without you.", 'carrie@icculus.org', $ip);
add_quote("How did I get so lucky as to find you.", 'carrie@icculus.org', $ip);
add_quote("You make me the luckiest person on the earth.", 'carrie@icculus.org', $ip);
add_quote("You have a beautiful smile.", 'carrie@icculus.org', $ip);
add_quote("I love you.", 'carrie@icculus.org', $ip);
add_quote("If you, me and my iphone were in a boat and it was sinking, I would save you.", 'carrie@icculus.org', $ip);
add_quote("I don't deserve someone so beautiful.", 'carrie@icculus.org', $ip);
add_quote("There is no one else for me.", 'carrie@icculus.org', $ip);
add_quote("You are the most important thing in my life.", 'carrie@icculus.org', $ip);
add_quote("You can have control of the tivo.", 'carrie@icculus.org', $ip);
add_quote("You can watch Dancing With the Stars on the big tv. I'll watch Heroes in the bedroom.", 'carrie@icculus.org', $ip);
add_quote("The tivo likes you better.", 'carrie@icculus.org', $ip);
add_quote("I think we shoud spend more time together.", 'carrie@icculus.org', $ip);
add_quote("I knew it was love from the first time I googled you.", 'carrie@icculus.org', $ip);

?>
